openapi: 3.0.0
info:
  version: '1.1'
  title: hotelbooking
  description: A service that uses a users hotel booking data to predict whether or not ther booking will be cancelled or not.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
    
paths:
  #arguments used to make dataset of user inputs
  /hotel/<hotel>/<leadtime>/<weekend>/<week>:
    get:
      tags:
        - Your Info
      operationId: prediction.arg
      description: Returns prediction of hotel booking
      responses:
        '200':
          description: 'Your hotel booking prediction'
  /file/<filename>:
    post:
      tags:
        - Upload
      summary: Upload a file 
      operationId: prediction.upload
      parameters:
        - name: file
          in: query
          description: upload csv of your hotel booking information 
          required: true
          schema:
            type: string 
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
servers:
- url: http://0.0.0.0:8080/hotelbooking